---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: Disable transparent huge pages on systemd systems
  ansible.builtin.include_tasks: disable_transparent_hugepages.yml
  when:
    - mongodb_transparent_hugepages_optimization | bool
    - ansible_service_mgr == "systemd"
    - mongodb_version_maj in ["4", "5", "6", "7"]

- name: Enable transparent huge pages on systemd systems
  ansible.builtin.include_tasks: enable_transparent_hugepages.yml
  when:
    - mongodb_transparent_hugepages_optimization | bool
    - ansible_service_mgr == "systemd"
    - mongodb_version_maj in ["8"]

- name: Install essential packages and set OS specific variables
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Install MongoDB dependencies
  ansible.builtin.package:
    name: "{{ mongodb_dep_pkg }}"
    state: present
  loop: "{{ mongodb_dependencies }}"
  loop_control:
    loop_var: mongodb_dep_pkg
  register: package_status
  until: package_status is success
  delay: 10
  retries: 6

- name: Verify that required string variables are defined
  ansible.builtin.assert:
    that: "{{ req_var }} is defined and {{ req_var }} | length > 0 and {{ req_var }} != None"
    fail_msg: "{{ req_var }} needs to be set for the role to work"
    success_msg: "{{ req_var }} is defined"
  loop:
    - mongodb_version
    - mongodb_os_distro
  loop_control:
    loop_var: req_var

- name: Check for mongod daemon
  ansible.builtin.stat:
    path: "{{ mongodb_path_exec }}/mongod"
  register: mongodb_local_binary

- name: Install MongoDB via package manager
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}-pkg-install.yml"
  when:
    - not mongodb_local_binary.stat.exists

- name: Enable Security Authorization and Create Users
  ansible.builtin.include_tasks: auth_init.yml
  when: mongodb_security_authorization == "disabled"

- name: Initialize MongoDB replicaset
  ansible.builtin.include_tasks: replicaset.yml
  when: mongodb_replication_replset is defined
